### ISSUE TITLE
How to fix findings?

### ISSUE THREAD

**Issue by FredSp1** [leoloobeek/LAPSToolkit#1]
Any tips for removing entries found with "Find-AdmPwdExtendedRights"? I have over 2800 entries I want to remove from various computer objects, non-delegated.
Thanks

**Comment by leoloobeek** [comment]
Sorry for the SUPER late response, I somehow missed this.

You can remove the “All Extended Rights” on a single host by following these steps:

1. Open up ADSI Edit
2. Right click on the computer object -> properties
3. Choose the security tab and select advanced
4. Find the affected user and select the row with ‘Special’ permission special-permissions
5. Uncheck ‘All Extended Rights’

**Comment by FredSp1** [comment]
Thanks. Would be great to have an automated way, take care of thousand objects at the same time.

Thanks,
Fred
